
database:
  enabled: false
  host: localhost
  database: db
  user: user
  pass: pass
  port: 3306
  ssl: true
  verify-certificate: true
  pool-size: 10
  max-lifetime: 1800

resource-pack: true

npc:
  default:
    location:
    hologram:
      - '&b&lDelivery'
      - '&fRight-Click to collect your deliveries'



enable-bstats: true